### PR TITLE
Added Copy To ClipBoard Button

### PR DESCRIPTION
**Pull request by salilgupta2510**
Let me know if any changes required.

### CODE REVIEW

**Comment by rodrigo-brito** [comment]
Very good! Works perfectly! But, when I used a big JSON for test, the button isn't visible, maybe if it stay on the bar or on top, looks better. Thanks for the contribution ❤️

**Comment by salilgupta2510** [comment]
@rodrigo-brito
Yeah you are right, the button displays after the text. Do you want the change, or is it fine this way?

**Comment by rodrigo-brito** [comment]
Can you change it?

**Comment by salilgupta2510** [comment]
Okay i will do it sometime today. Can you close this PR? i will create a new PR when i am done with it :)

**Comment by rodrigo-brito** [comment]
No problem, thank you!

**Pull request merged**
